# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand1', models.IntegerField(max_length=5)),
                ('operand2', models.IntegerField(max_length=5)),
                ('operator', models.CharField(max_length=5)),
                ('total', models.IntegerField(max_length=10)),
            ],
        ),
    ]
