# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='total',
            field=models.IntegerField(max_length=5),
        ),
    ]
